# {% include './common.yaml' %}

assets_subdir: "dark"
background_color: "{{ palette.gray1 }}"
background_color_alt: "{{ palette.gray2 }}"
background_color_alt2: "{{ palette.black }}"
background_color_disabled: "#181818"
border_color: "#444444"
button_pressed: "#2d2d2d"
checkbox_check: "{{ palette.white }}"
combobox: "#1f1f27"
highlight: "{{ palette.white }}"
hscrollbar: "#666666"
hscrollbar_groove: "#111111"
item_handle: "{{ palette.white }}"
text_background_color: "#1f1f27"
text_color: "{{ palette.white }}"
text_color_alt: "{{ palette.black }}"
text_color_disabled: "#d0d0d0"
tab_selected: "#1e1e1e"
track_panel_background: "{{ palette.gray1 }}"
transport_clock_background: "#1e1e1e"
vscrollbar: "#666666"
vscrollbar_groove: "#111111"
